language: android
jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-21

android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-tv-l
    - add-on
    - extra

before_install:
  - sudo apt-get clean
  - sudo apt-get update -y
  - sudo apt-get install -y libstdc++6:i386 lib32z1 build-essential autoconf automake libtool expect
  - sudo pip install codecov
  - curl -L http://dl.google.com/android/ndk/android-ndk-r9-linux-x86_64.tar.bz2 > ndk.tar.bz2
  - sudo tar -C /opt -jxf ndk.tar.bz2
  - export NDK_PROJECT_PATH=$PWD

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - chmod u+x android-wait-for-emulator
  - ./android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew build connectedAndroidTest

